INSERT INTO LIGA (NAME) VALUES ('Main');

INSERT INTO DIVISION (LIGA_ID, NAME) VALUES (1, 'Division 1');
INSERT INTO DIVISION (LIGA_ID, NAME) VALUES (1, 'Division 2');

INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (1, 'Ence');
INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (1, 'G2');
INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (2, 'Astralis');
INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (2, 'BIG');

INSERT INTO GAME (DIVISION_ID, NAME) VALUES (1, 'Game 1');
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (2, 1);


