INSERT INTO LIGA (NAME) VALUES ('Main');
INSERT INTO LIGA (NAME) VALUES ('Second');

INSERT INTO DIVISION (LIGA_ID, NAME) VALUES (1, 'Division 1');
INSERT INTO DIVISION (LIGA_ID, NAME) VALUES (1, 'Division 2');

INSERT INTO DIVISION (LIGA_ID, NAME) VALUES (2, 'Subdivision 1');
INSERT INTO DIVISION (LIGA_ID, NAME) VALUES (2, 'Subdivision 2');

INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (1, 'Ence');
INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (1, 'G2');
INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (2, 'Astralis');
INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (2, 'BIG');
INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (3, 'LDLC');
INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (3, 'ALTERNATE aTTax');
INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (4, 'Coppenhagen Wolfes');
INSERT INTO TEAM (DIVISION_ID, NAME) VALUES (4, 'Unicorns of Love');

INSERT INTO GAME (DIVISION_ID, NAME, WINNER_TEAM_ID) VALUES (1, 'Game 1', 2);
INSERT INTO GAME (DIVISION_ID, NAME, WINNER_TEAM_ID) VALUES (1, 'Game 2', 1);
INSERT INTO GAME (DIVISION_ID, NAME, WINNER_TEAM_ID) VALUES (2, 'Game 3', 3);
INSERT INTO GAME (DIVISION_ID, NAME, WINNER_TEAM_ID) VALUES (2, 'Game 4', 4);
INSERT INTO GAME (DIVISION_ID, NAME, WINNER_TEAM_ID) VALUES (3, 'Game 5', 6);
INSERT INTO GAME (DIVISION_ID, NAME, WINNER_TEAM_ID) VALUES (3, 'Game 6', 5);
INSERT INTO GAME (DIVISION_ID, NAME, WINNER_TEAM_ID) VALUES (4, 'Game 7', 7);
INSERT INTO GAME (DIVISION_ID, NAME, WINNER_TEAM_ID) VALUES (4, 'Game 8', 8);

INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (1, 1);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (2, 1);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (1, 2);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (2, 2);

INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (3, 3);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (4, 3);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (3, 4);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (4, 4);

INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (5, 5);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (6, 5);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (5, 6);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (6, 6);

INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (7, 7);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (8, 7);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (7, 8);
INSERT INTO TEAM_GAME (TEAM_ID, GAME_ID) VALUES (8, 8);

